server:
  service:
    type: LoadBalancer  # or ClusterIP + ingress

  ingress:
    enabled: true
    hosts:
      - argocd.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
    # tls:
    #   - secretName: argocd-tls
    #     hosts:
    #       - argocd.example.com

configs:
  cm:
    # Customize as needed
    disableTelemetry: "true"

admin:
  # You should set a bcrypt-hashed password or configure SSO for adminpass
  password: $2a$12$RcRV5H5X0Hu6RFGJc1odT.0YMBQ/9ATh3D38oKyiZqOyQssMWq.xC  
